### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by ghost** [zoang/wsl-ubuntu#1]
在没有更换软件源的时候使用 apt update 和 apt upgrade 命令会非常慢。。虽然手动替换一下也不是很麻烦，但是这样脚本里的替换软件源的操作感觉就没用了...
apt update 和  apt upgrade 只能手动，不能放在脚本里嘛？我不太会shell脚本，只是一个想法

**Comment by zoang** [comment]
已更新，已经好久没上GIT了。
